FROM prom/node-exporter:latest

LABEL maintainer="Tarek Deshli <totti786@gmail.com>"
LABEL description="Node Exporter for LDAP monitoring"

EXPOSE 9100

ENTRYPOINT ["/bin/node_exporter"]
CMD ["--path.procfs=/host/proc", "--path.sysfs=/host/sys", "--path.rootfs=/rootfs"]
